# Generated by Django 5.1.5 on 2025-01-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_bio_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_bio_ru',
            field=models.TextField(null=True),
        ),
    ]
