# Generated by Django 5.1.5 on 2025-01-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_status',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_status',
        ),
    ]
