# Generated by Django 5.1.5 on 2025-01-16 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assig_title',
            new_name='title',
        ),
    ]
