# Generated by Django 5.1.5 on 2025-01-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0002_student_student_bio_en_student_student_bio_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherreview',
            name='stars',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
