# Generated by Django 5.1.5 on 2025-01-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0003_category_category_name_en_category_category_name_ru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Students', 'verbose_name_plural': 'Students_Profile'},
        ),
    ]
