# Generated by Django 5.1.5 on 2025-01-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0003_teacherreview_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherreview',
            name='stars',
            field=models.IntegerField(blank=True, choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
