# Generated by Django 5.1.5 on 2025-01-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0004_alter_teacherreview_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(related_name='course', to='udemy.category'),
        ),
    ]
