# Generated by Django 5.1.5 on 2025-01-20 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0007_alter_teacherrating_teacher_coursereview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherreview',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='udemy.teacher'),
        ),
    ]
