# Generated by Django 5.1.5 on 2025-01-20 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0008_alter_teacherreview_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udemy.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udemy.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udemy.teacher')),
            ],
        ),
    ]
