# Generated by Django 5.1.5 on 2025-01-21 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0009_alter_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_age',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(65)]),
        ),
    ]
